### PR TITLE
CI

### PR DESCRIPTION
**Pull request by Shimogawa**
你是一个，一个一个一个ci

### CODE REVIEW

**Comment by Shimogawa** [comment]
怎么有852个error

**Comment by Shimogawa** [comment]
https://github.com/chuigda/Project-705/security/code-scanning?query=is%3Aopen+branch%3Amaster+pr%3A32+

难道是只能用node 16

**Comment by chuigda** [comment]
> https://github.com/chuigda/Project-705/security/code-scanning?query=is%3Aopen+branch%3Amaster+pr%3A32+
> 
> 难道是只能用node 16

看起来eslint在node 15上坏坏，说起来你用的哪个版本

**Comment by Shimogawa** [comment]
> > https://github.com/chuigda/Project-705/security/code-scanning?query=is%3Aopen+branch%3Amaster+pr%3A32+
> > 难道是只能用node 16
> 
> 看起来eslint在node 15上坏坏，说起来你用的哪个版本

开发用了16，那 build 也只用16算了

**Comment by chuigda** [comment]
图片

Yes, node15 will not work without changing our dependencies. This is not actually a bug, but just sticking to node v16 would be fine.

**Comment by chuigda** [comment]
It will KEAL.

**Pull request merged**
